SELECT DISTINCT CITY
FROM STATION
WHERE 
CITY LIKE 'a%' 
or CITY  LIKE 'e%' 
or CITY LIKE 'i%' 
or CITY LIKE 'o%' 
or CITY LIKE 'u%'
or CITY LIKE 'A%' 
or CITY LIKE 'E%' 
or CITY LIKE 'I%' 
or CITY LIKE 'O%'
or CITY  LIKE 'U%' ;
